# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo test
  displayName: 'Download and Installing Vorteil'

- script: |
    wget https://downloads.vorteil.io/vcli/3.1.1/linux/vorteil-3.1.1-installer.run
    chmod +x ./vorteil-3.1.1-installer.run
    sudo ./vorteil-3.1.1-installer.run --mode unattended
    vorteil version
    wget https://storage.googleapis.com/vorteil-dl/vorteil.license
    vorteil license register vorteil.license
    vorteil license info
    az help
  displayName: 'Run a multi-line script'
